### ISSUE TITLE
NPM can't find coreui icons

### ISSUE THREAD

**Issue by YuriAraujo** [coreui/coreui-icons#1]
I'm trying to install coreui icons through `npm install` and everytime I got this error:

> npm ERR! code E404
> npm ERR! 404 Not Found: @coreui/icons@^0.2.0

And I get the same error trying to install with `npm install @coreui/icons --save`

Here's the log:
```
2900 verbose stack Error: 404 Not Found: @coreui/icons@^0.2.0
2900 verbose stack     at fetch.then.res (/home/yuri/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
2900 verbose stack     at tryCatcher (/home/yuri/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2900 verbose stack     at Promise._settlePromiseFromHandler (/home/yuri/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
2900 verbose stack     at Promise._settlePromise (/home/yuri/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
2900 verbose stack     at Promise._settlePromise0 (/home/yuri/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
2900 verbose stack     at Promise._settlePromises (/home/yuri/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
2900 verbose stack     at Async._drainQueue (/home/yuri/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
2900 verbose stack     at Async._drainQueues (/home/yuri/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
2900 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/home/yuri/.nvm/versions/node/v10.2.1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
2900 verbose stack     at runCallback (timers.js:696:18)
2900 verbose stack     at tryOnImmediate (timers.js:667:5)
2900 verbose stack     at processImmediate (timers.js:649:5)
2901 verbose cwd /home/yuri/repos/cp-frontend2
2902 verbose Linux 4.14.57-1-MANJARO
2903 verbose argv "/home/yuri/.nvm/versions/node/v10.2.1/bin/node" "/home/yuri/.nvm/versions/node/v10.2.1/bin/npm" "install"
2904 verbose node v10.2.1
2905 verbose npm  v6.2.0
2906 error code E404
2907 error 404 Not Found: @coreui/icons@^0.2.0
2908 verbose exit [ 1, true ]
```

My environment:
Manjaro: GNOME 17.1.11
Node: 10.2.1
NVM: 0.33.11

**Comment by xidedix** [comment]
@YuriAraujo please try to reset npm cache with `npm cache clean`

**Comment by YuriAraujo** [comment]
It was problem with npm cache, I've fixed it using `npm cache verify` (I got scared to do a reset)
